### ISSUE TITLE
Support for IUnit::Experience() and IUnit::MaxExperience()

### ISSUE THREAD

**Issue by tsuhgi** [MyriadSoft/League-SDK#14]

**Comment by RethoughtSolutions** [comment]
I second this, needed it as well.

**Comment by MyriadSoft** [comment]
Experience added and will be in the next update, you can check MaxExperience here for reference. http://leagueoflegends.wikia.com/wiki/Experience_(summoner)

**Comment by MyriadSoft** [comment]
Experience has been added and will be in the next update. Please use the following reference sheet to implement MaxExperience from your plugin. http://leagueoflegends.wikia.com/wiki/Experience_(champion)

**Comment by MyriadSoft** [comment]
Added and will be in the next update.
