### ISSUE TITLE
IUnit::GetObjectStartTime

### ISSUE THREAD

**Issue by zFederaL** [MyriadSoft/League-SDK#15]

**Comment by RethoughtSolutions** [comment]
Hello! Your issue is a bit unspecific. I asume you want that member to get added to the IUnit class.
Can you give a brief description of what it is supposed to do? I guess that you want it to save the time when an object got created.

**Comment by zFederaL** [comment]
Yes save the time when an object got created

**Comment by MyriadSoft** [comment]
Is there a reason you need this and can't implement it yourself in a plugin? You can use an OnCreateObject event to store start times in a map,

**Comment by MyriadSoft** [comment]
I'm closing this for now as it can be done within plugins and I haven't received a response in 4 days.
