### ISSUE TITLE
Prediction bugs.

### ISSUE THREAD

**Issue by Korn1s** [MyriadSoft/League-SDK#29]
Cassiopeia Q is casting always behind target when it's running, also it tries to cast Q even if target is out of my range and it misses. Example: https://i.gyazo.com/b9d4653d0a9fbe71c8707d3f1b7787de.mp4

**Comment by MyriadSoft** [comment]
This works completely fine for me, make sure your spell values are set correctly and reopen if you're still having the same issue.
