### ISSUE TITLE
Logging crashes Brian (TheLegend27)

### ISSUE THREAD

**Issue by RethoughtSolutions** [MyriadSoft/League-SDK#33]
Currently crashes are not getting logged. I've just had a user not knowing why his game is crashing. http://i.imgur.com/zzr1Edy.png Is there some way of logging?

 This issue was automatically generated through our Discord Server. For more informations direct message Rethought.

**Comment by MyriadSoft** [comment]
This is done and the next update will have more advanced crash logging.
