### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by diejozef** [MyriadSoft/League-SDK#34]
- Add MF's passive to dmg calcs
- Add upgraded versions of DrawLine, DrawOutlinedBox, etc. with anti-aliasing
- Add anti-aliasing flag to fonts(and optimize IFont pls)
- Add OnTeleport(handle shen ult, recall, summoner spell, tf ult)
- Add IMenuOption::UpdateEnabled, UpdateDisplayName, Remove
- Add support for mastery information
- Access to default menu elements(e.g Orbwalker::ExtraWindupTime)
- Extend SendPing/ShowPing with champions(alive/dead), jungle timers, summoner spells, etc.
- Extend IUnit with MagicDamageTaken, PhysicalDamageTaken, TrueDamageTaken, WardsPlaced, VisionWardsPlaced, Double-, Triple-, Quadra-, PentaKills, TotalGoldEarned, Gold, Experience, MagicDamageDealt, PhysicalDamageDealt, TrueDamageDealt, Deaths, Assists, Kills, TotalHeal(amount of healing done), TotalGoldEarnedByTeam / etc.

**Comment by MyriadSoft** [comment]
Closing this as these issues have been recreated separately by Bryan.
