### ISSUE TITLE
Mastery support issued byBrian (TheLegend27)

### ISSUE THREAD

**Issue by RethoughtSolutions** [MyriadSoft/League-SDK#40]
Add support for mastery information,  repost from https://github.com/MyriadSoft/League-SDK/issues/34

 This issue was automatically generated through our Discord Server. For more informations direct message the owner of RethoughtBot.

**Comment by Harmenszoon** [comment]
Second this please (for damage calculations especially)

**Comment by MyriadSoft** [comment]
This is done and will be in the next update.
