### ISSUE TITLE
IUnit* Functions

### ISSUE THREAD

**Issue by tr33s** [MyriadSoft/League-SDK#41]
Need:
- IsAlly()
- IsEnemy()
- IsNeutral()
- IsZombie()

**Comment by RethoughtSolutions** [comment]
We got GetTeam and IsEnemy(IUnit)

Dunno about the other 2.

**Comment by MyriadSoft** [comment]
Use GetTeam().

**Comment by tr33s** [comment]
Sounds great way to waste like 50 chars.

And IsZombie is not a team related fn!
