### ISSUE TITLE
float IUnit::ArmorPenetrationFlat() incorrect values returned

### ISSUE THREAD

**Issue by Harmenszoon** [MyriadSoft/League-SDK#46]
Seems that it always returns 1.0000?   Probably has to do with the lethality update.

**Comment by MyriadSoft** [comment]
This is accurate, if you have 7% armor penetration with 5/5 Battering Blows mastery then it will be 0.93. If you see 1.0 then that just means you have no flat armor penetration.

**Comment by MyriadSoft** [comment]
Fixed for lethality and will be in the next update.
