### ISSUE TITLE
FindBestCastPosition using CastFrom spells for farming (viktor E)

### ISSUE THREAD

**Issue by dewblackio2** [MyriadSoft/League-SDK#54]
FindBestCastPosition only returns the end position of the cast, can you add params: Input spells Cast Range, alongside Spells Max range, and a Vec3 StartPosition which returns a position within Cast Range to start the line cast, and then the cast position returns a position that can reach up to the Spells full range. Maybe something like:
```C++
virtual void FindBestCastPosition(float CastRange, float SpellLength, float SpellRange, float Radius, bool IsMissile, bool CheckMinions, bool CheckHeroes, Vec3& StartPosition, Vec3& CastPosition, int& HitEnemyCount) = 0;
```
Edit: Added SpellLength param since you need to consider how long the line is on the cast, if we were to cast the E sideways, we want to make sure the line is the proper length to calculate # of minions hit correctly

**Comment by dewblackio2** [comment]
It'd be used like this:
`CPP
int EHit;
Vec3 startpos;
Vec3 castpos;
GPrediction->FindBestCastPosition(500.f, 525.f, 1025.f, 70.f, false, true, false, startpos, castpos, EHit);`

**Comment by tr33s** [comment]
Would be nice if it returned the units hit in general as well.

**Comment by dewblackio2** [comment]
yea maybe add a param that returns a std::vector<IUnit*> list of targets hit following the check heroes and check minions params

**Comment by MyriadSoft** [comment]
Added and will be in the next update.
