### ISSUE TITLE
Azir's Soldiers don't have an Attack Range?

### ISSUE THREAD

**Issue by dewblackio2** [MyriadSoft/League-SDK#58]
using soldier->AttackRange() returns 0. but in game you can see the blue circle the game draws showing the soldiers AA range. I'll write it manually for now, but i'm just saying they don't have an auto attack range in the core lol

**Comment by MyriadSoft** [comment]
AttackRange() will only be valid for certain object types, the engine obviously uses something different for Azir soldiers. Basically anything that's non zero in GetType() will work.
