### ISSUE TITLE
[Request] Spell Name in ISpell2 initializer

### ISSUE THREAD

**Issue by RyTak** [MyriadSoft/League-SDK#7]
If we allow names to be populated on spell initialization, we can create multiple spells on the same slot, making it easier to shorthand calls and checks for spells that belong to champions with 2 forms. It can also be used for toggle checks like on AatroxW for instance where you can swap between heal and damage buff.

**Comment by RyTak** [comment]
Instead of having it in the CreateSpell2 init, something along the lines how we have SetSkillshot.
Q->SetSkillshot (args)
Q->SetName(Name)

Q2->SetSkillshot (args)
Q2->SetName(Name).

that way we can dont have to scrape for spell names from game and it'd be able to read them on the fly while doing void IsMelee() and void IsRanged() without needing to scrape the game for every spell to check for combo logics.

**Comment by MyriadSoft** [comment]
Added and will be in the next update.
