### ISSUE TITLE
 FindBestCastPosition

### ISSUE THREAD

**Issue by RyTak** [MyriadSoft/League-SDK#77]
Have FindBestCastPosition (if it includes wards) to not include wards, as we can get wards through the GetAllUnits callback. Reasoning being that wards are not minions and cause junk data to be included in the callback in question, resulting in poor usage of spells and items. 

Also, another issue with wards:
In the event that a ward is placed in vision, most assemblies read the ward as a very low HP minion, causing it to use mana on a technically unkillable object, as wards require auto attacks and not spells to be destroyed.

**Comment by MyriadSoft** [comment]
GetAllMinions actually includes wards which I don't think most plugin developers were aware of because it's strangely named and wasn't documented. It's fixed and will be in the next update.
