### ISSUE TITLE
Tower Range

### ISSUE THREAD

**Issue by LordZEDith** [MyriadSoft/League-SDK#8]
Please Add Tower Range. Thanks 👍

**Comment by RethoughtSolutions** [comment]
The Turret Range could be its AutoAttack range.
Other than that:
LolWiki provides your with ranges. Add the BoundingRadius of the champion to it to get the range.

**Comment by LordZEDith** [comment]
I know I can do this but I I want it implemented how L# had it where its showed the color when it aggro's you and when it does't just like L#.

**Comment by MyriadSoft** [comment]
Everything needed is already available to be done with plugins.
